{
    perform: true,
    alwaysRequireAssignee: false,
    labelsRequiringAssignee: [],
    autoAssignees: {
        L10N: [],
        VIM: [],
        api: [],
        cli: [],
        color-palette: [],
        config: [],
        css-less-scss: [],
        debug-console: [],
        debug: [],
        diff-editor: [],
        dropdown: [],
        editor: [],
        editor-1000-limit: [],
        editor-autoclosing: [],
        editor-autoindent: [],
        editor-brackets: [],
        editor-clipboard: [],
        editor-code-actions: [],
        editor-code-lens: [],
        editor-color-picker: [],
        editor-colors: [],
        editor-columnselect: [],
        editor-commands: [],
        editor-contrib: [],
        editor-drag-and-drop: [],
        editor-find: [],
        editor-folding: [],
        editor-hover: [],
        editor-ime: [],
        editor-input: [],
        editor-ligatures: [],
        editor-links: [],
        editor-minimap: [],
        editor-multicursor: [],
        editor-parameter-hints: [],
        editor-rendering: [],
        editor-smooth: [],
        editor-symbols: [],
        editor-textbuffer: [],
        editor-wrapping: [],
        emmet: [],
        error-list: [],
        explorer-custom: [],
        extension-host: [],
        extensions: [],
        file-decorations: [],
        file-encoding: [],
        file-explorer: [],
        file-glob: [],
        file-io: [],
        file-watcher: [],
        formatting: [],
        git: [],
        grammar: [],
        hot-exit: [],
        html: [],
        install-update: [],
        integrated-terminal: [],
        integration-test: [],
        intellisense-config: [],
        issue-reporter: [],
        javascript: [],
        json: [],
        keyboard-layout: [],
        keybindings: [],
        keybindings-editor: [],
        lang-diagnostics: [],
        languages basic: [],
        list: [],
        log: [],
        markdown: [],
        marketplace: [],
        menus: [],
        merge-conflict: [],
        multi-root: [],
        os-integration: [],
        outline: [],
        output: [],
        perf-profile: [],
        perf-bloat: [],
        perf-startup: [],
        php: [],
        proxy: [],
        quick-pick: [],
        release-notes: [],
        remote: [],
        rename: [],
        run-as-admin: [],
        samples: [],
        scm: [],
        search: [],
        search-replace: [],
        settings-editor: [],
        shared-process: [],
        smart-select: [],
        smoke-test: [],
        snippets: [],
        suggest: [],
        tasks: [],
        telemetry: [],
        themes: [],
        tokenization: [],
        tree: [],
        typescript: [],
        unit-test: [],
        uri: [],
        ux: [],
        vscode-build: [],
        webview: [],
        workbench: [],
        workbench-diagnostics: [],
        workbench-dnd: [],
        workbench-editors: [],
        workbench-electron: [],
        workbench-feedback: [],
        workbench-grid: [],
        workbench-history: [],
        workbench-layout: [],
        workbench-menu: [],
        workbench-notifications: [],
        workbench-state: [],
        workbench-status: [],
        workbench-tabs: [],
        workbench-title: [],
        workbench-touchbar: [],
        workbench-views: [],
        workbench-welcome: []
    }
}
