{
    perform: false,
    alwaysRequireAssignee: false,
    labelsRequiringAssignee: [],
    autoAssignees: {
        accessibility: [],
        acquisition: [],
        agent: [],
        azure: [],
        backup: [],
        bcdr: [],
        'chart viewer': [],
        connection: [],
        dacfx: [],
        dashboard: [],
        'data explorer': [],
        documentation: [],
        'edit data': [],
        export: [],
        extensibility: [],
        extensionManager: [],
        globalization: [],
        grid: [],
        import: [],
        insights: [],
        intellisense: [],
        localization: [],
        'managed instance': [],
        notebooks: [],
        'object explorer': [],
        performance: [],
        profiler: [],
        'query editor': [],
        'query execution': [],
        reliability: [],
        restore: [],
        scripting: [],
        'server group': [],
        settings: [],
        setup: [],
        shell: [],
        showplan: [],
        snippet: [],
        sql2019Preview: [],
        sqldw: [],
        supportability: [],
        ux: []
    }
}
