# actions for Needs Logs label
Needs Logs:
  comment: |
    We need more info to debug your particular issue. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster.
    1. First open the Settings page, find the `Mssql: Tracing Level` setting and change that to `All` then restart Azure Data Studio.
    2. Open command palette (Click **View** -> **Command Palette**) and run the command `Developer: Set Log Level...` and set the level to `Trace`.
    3. Run the repro scenarios.
    4. Collect the following logs:

      **Console Logs**
      - Open Developer Tools (Help -> Toggle Developer Tools)
      - Click the **Console** tab
      - Click in the log area and select all text (CTRL+A)
      - Save this text into a file named console.log and attach it to this issue.
      - Developer Tools can be closed via Help -> Toggle Developer Tools

      **Application Logs**
      - Open command palette (Click **View** -> **Command Palette**)
      - Run the command: **`Developer: Open Logs Folder`**
      - This will open the log folder locally. Please zip up this folder and attach it to the issue.
    5. Now you can revert the Log/Tracing levels changes made in step 1 and step 2.

# actions for Needs Logs - Azure label
Needs Logs - Azure:
  comment: |
    We need more info to debug your Azure Active Directory issue. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster.

    - In the settings menu, find the setting titled `Azure: Logging Level` and select the `Verbose` option
    - Restart Azure Data Studio
    - Run the process that produces your error
    - Open command palette (Click **View** -> **Command Palette**)
    - Run the command: **`Developer: Open Logs Folder`**
    - Follow this path to find the Azure Accounts log file: `[default log folder]/window1/exthost/output_logging_[earliest timestamp]/#-Azure Accounts.log`
    - Please attach the Azure-Accounts.log file to the issue.

# actions for Out of Scope label
Out of Scope:
  comment: "Thank you for your feedback! This feature is currently out of scope and we do not plan to work on it in a currently planned release. We will close this issue to keep our backlog focused on requests that we are planning to work on. Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested."
  close: true
