steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.1'
  displayName: 'Install Node.js'

- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
  inputs:
    keyfile: '.yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
    vstsFeed: '$(ArtifactFeed)'

- script: |
    yarn
  displayName: 'Yarn Install'
  condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))

- task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
  inputs:
    keyfile: '.yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
    vstsFeed: '$(ArtifactFeed)'
  condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))

- script: |
    yarn gulp electron-x64
  displayName: 'Electron'

- script: |
    yarn gulp hygiene
  displayName: Run Hygiene Checks

- script: |
    yarn tslint
  displayName: 'Run TSLint'

- script: |
    yarn strict-null-check
  displayName: 'Run Strict Null Check'

- script: |
    yarn compile
  displayName: 'Compile'

- script: |
    .\scripts\test.bat --reporter mocha-junit-reporter --coverage
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'test-results.xml'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: $(System.DefaultWorkingDirectory)\.build\coverage\cobertura-coverage.xml
    reportDirectory: $(System.DefaultWorkingDirectory)\.build\coverage\lcov-report
