// Generated by typings
// Source: node_modules/@angular/platform-browser-dynamic/src/platform_providers.d.ts
declare module '~@angular/platform-browser-dynamic/src/platform_providers' {
import { Provider } from '@angular/core';
export const INTERNAL_BROWSER_DYNAMIC_PLATFORM_PROVIDERS: Provider[];
}
declare module '@angular/platform-browser-dynamic/src/platform_providers' {
export * from '~@angular/platform-browser-dynamic/src/platform_providers';
}

// Generated by typings
// Source: node_modules/@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl.d.ts
declare module '~@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl' {
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import { ResourceLoader } from '@angular/compiler';
export class ResourceLoaderImpl extends ResourceLoader {
    get(url: string): Promise<string>;
}
}
declare module '@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl' {
export * from '~@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl';
}

// Generated by typings
// Source: node_modules/@angular/platform-browser-dynamic/src/private_export.d.ts
declare module '~@angular/platform-browser-dynamic/src/private_export' {
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
export { INTERNAL_BROWSER_DYNAMIC_PLATFORM_PROVIDERS as ɵINTERNAL_BROWSER_DYNAMIC_PLATFORM_PROVIDERS } from '~@angular/platform-browser-dynamic/src/platform_providers';
export { ResourceLoaderImpl as ɵResourceLoaderImpl } from '~@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl';
}
declare module '@angular/platform-browser-dynamic/src/private_export' {
export * from '~@angular/platform-browser-dynamic/src/private_export';
}

// Generated by typings
// Source: node_modules/@angular/platform-browser-dynamic/src/version.d.ts
declare module '~@angular/platform-browser-dynamic/src/version' {
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
/**
 * @module
 * @description
 * Entry point for all public APIs of the common package.
 */
import { Version } from '@angular/core';
/**
 * @stable
 */
export const VERSION: Version;
}
declare module '@angular/platform-browser-dynamic/src/version' {
export * from '~@angular/platform-browser-dynamic/src/version';
}

// Generated by typings
// Source: node_modules/@angular/platform-browser-dynamic/src/platform-browser-dynamic.d.ts
declare module '~@angular/platform-browser-dynamic/src/platform-browser-dynamic' {
import { PlatformRef, Provider } from '@angular/core';
export * from '~@angular/platform-browser-dynamic/src/private_export';
export { VERSION } from '~@angular/platform-browser-dynamic/src/version';
/**
 * @experimental
 */
export const RESOURCE_CACHE_PROVIDER: Provider[];
/**
 * @stable
 */
export const platformBrowserDynamic: (extraProviders?: Provider[] | undefined) => PlatformRef;
}
declare module '@angular/platform-browser-dynamic/src/platform-browser-dynamic' {
export * from '~@angular/platform-browser-dynamic/src/platform-browser-dynamic';
}

// Generated by typings
// Source: node_modules/@angular/platform-browser-dynamic/platform-browser-dynamic.d.ts
declare module '~@angular/platform-browser-dynamic/platform-browser-dynamic' {
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
/**
 * @module
 * @description
 * Entry point for all public APIs of the platform-browser-dynamic package.
 */
export * from '~@angular/platform-browser-dynamic/src/platform-browser-dynamic';
}
declare module '@angular/platform-browser-dynamic/platform-browser-dynamic' {
export * from '~@angular/platform-browser-dynamic/platform-browser-dynamic';
}
declare module '@angular/platform-browser-dynamic' {
export * from '~@angular/platform-browser-dynamic/platform-browser-dynamic';
}
