/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the Source EULA. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { AppContext } from '../appContext';
import * as azdata from 'azdata';
import * as vscode from 'vscode';
import { sqlProviderName } from '../constants';
import { generateUuid } from 'vscode-languageclient/lib/utils/uuid';
import { fillServerInfo } from '../telemetry';
import * as telemetry from '@microsoft/ads-extension-telemetry';
import * as nls from 'vscode-nls';
import { getConfigPreloadDatabaseModel, setConfigPreloadDatabaseModel } from '../utils';
const localize = nls.loadMessageBundle();

const NewTableText = localize('tableDesigner.NewTable', "New Table");
const DidInformUserKey: string = 'tableDesigner.DidInformUser';

export function registerTableDesignerCommands(appContext: AppContext) {
	appContext.extensionContext.subscriptions.push(vscode.commands.registerCommand('mssql.newTable', async (context: azdata.ObjectExplorerContext) => {
		void showPreloadDbModelSettingPrompt(appContext);
		const connectionString = await azdata.connection.getConnectionString(context.connectionProfile.id, true);
		const tableIcon = context.nodeInfo.nodeSubType as azdata.designers.TableIcon;
		const telemetryInfo = await getTelemetryInfo(context, tableIcon);
		await azdata.designers.openTableDesigner(sqlProviderName, {
			title: NewTableText,
			tooltip: tableDesignerTitleGenerator(connectionString, context.connectionProfile, NewTableText),
			server: context.connectionProfile.serverName,
			database: context.connectionProfile.databaseName,
			isNewTable: true,
			id: generateUuid(),
			connectionString: connectionString,
			accessToken: context.connectionProfile.options.azureAccountToken,
			tableIcon: tableIcon
		}, telemetryInfo);
	}));

	appContext.extensionContext.subscriptions.push(vscode.commands.registerCommand('mssql.designTable', async (context: azdata.ObjectExplorerContext) => {
		void showPreloadDbModelSettingPrompt(appContext);
		const server = context.connectionProfile.serverName;
		const database = context.connectionProfile.databaseName;
		const schema = context.nodeInfo.metadata.schema;
		const name = context.nodeInfo.metadata.name;
		const connectionString = await azdata.connection.getConnectionString(context.connectionProfile.id, true);
		const tableIcon = context.nodeInfo.nodeSubType as azdata.designers.TableIcon;
		const telemetryInfo = await getTelemetryInfo(context, tableIcon);
		await azdata.designers.openTableDesigner(sqlProviderName, {
			title: `${schema}.${name}`,
			tooltip: tableDesignerTitleGenerator(connectionString, context.connectionProfile, `${schema}.${name}`),
			server: server,
			database: database,
			isNewTable: false,
			name: name,
			schema: schema,
			id: `${sqlProviderName}|${server}|${database}|${schema}|${name}`,
			connectionString: connectionString,
			accessToken: context.connectionProfile.options.azureAccountToken,
			tableIcon: tableIcon
		}, telemetryInfo);
	}));
}

async function getTelemetryInfo(context: azdata.ObjectExplorerContext, tableType: string): Promise<telemetry.TelemetryEventProperties> {
	const serverInfo = await azdata.connection.getServerInfo(context.connectionProfile.id);
	const telemetryInfo: telemetry.TelemetryEventProperties = {
		tableType
	};
	fillServerInfo(telemetryInfo, serverInfo);
	return telemetryInfo;
}

async function showPreloadDbModelSettingPrompt(appContext: AppContext): Promise<void> {
	// skip if the setting is already enabled.
	if (getConfigPreloadDatabaseModel()) {
		return;
	}

	// only show the prompt once.
	const didInformUser = appContext.extensionContext.globalState.get<boolean>(DidInformUserKey);
	if (!didInformUser) {
		void appContext.extensionContext.globalState.update(DidInformUserKey, true);
	} else {
		return;
	}
	const yesOption = localize('tableDesigner.yes', "Yes");
	const noOption = localize('tableDesigner.no', "No");

	const result = await vscode.window.showInformationMessage(localize('tableDesigner.turnOnPreloadingMessage', "Do you want to reduce the table designer load time by enabling the database model preloading? The database model will be preloaded when you expand the database node in object explorer."), yesOption, noOption);
	if (result === yesOption) {
		setConfigPreloadDatabaseModel(true);
	}
}

// Since this title is also generated by STS, we cannot use the connection profile title generator found in Connection Management Service
// To avoid inconsistencies, we will have to create a title based on what is available to STS as well as appending the connection name.
// All non empty options (default or not) will be included because non default strings aren't defined in STS as well.
function tableDesignerTitleGenerator(connectionString: string, connectionProfile: azdata.IConnectionProfile, schemaName: string): string {
	let finalString = '';
	let connectionName = connectionProfile.connectionName

	if (!!connectionName && connectionName !== '') {
		finalString += '[\"' + connectionName + '\"]: ';
	}

	finalString += `${connectionProfile.serverName} - ${connectionProfile.databaseName} - ${schemaName}`;

	finalString += ' (';

	let propertiesArray = connectionString.split(";");

	for (let i = 0; i < propertiesArray.length; i++) {
		let partArray = propertiesArray[i].split('=');
		let value = '';
		let key = partArray[0];
		if (partArray.length > 1) {
			value = partArray[1];
		}
		if (value !== '' && key !== 'Data Source' && key !== 'Initial Catalog' && key !== 'Password' && propertiesArray[i] !== 'Application Name=sqlops-connection-string') {
			finalString += propertiesArray[i] + ';';
		}
	}

	finalString = finalString.slice(0, -1);
	finalString += ')';

	return finalString;
}
