#!/bin/bash
# Bash script to check for missing yarn.lock files in extensions and create them
# Usage: ./scripts/check-and-fix-yarn-locks.sh

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Checking for missing yarn.lock files in extensions...${NC}"

# Function to check for missing yarn.lock files
check_missing_yarn_locks() {
    echo -e "\n${CYAN}Checking for missing yarn.lock files:${NC}"
    local missing_count=0
    
    for extension_dir in extensions/*/; do
        if [ -d "$extension_dir" ]; then
            extension_name=$(basename "$extension_dir")
            package_json_path="${extension_dir}package.json"
            yarn_lock_path="${extension_dir}yarn.lock"
            
            if [ -f "$package_json_path" ]; then
                if [ ! -f "$yarn_lock_path" ]; then
                    echo -e "${RED}Missing yarn.lock: $extension_name${NC}"
                    ((missing_count++))
                fi
            fi
        fi
    done
    
    if [ $missing_count -eq 0 ]; then
        echo -e "${GREEN}✓ All extensions with package.json have yarn.lock files${NC}"
    else
        echo -e "${RED}Found $missing_count extensions missing yarn.lock files${NC}"
    fi
    
    return $missing_count
}

# Function to create missing yarn.lock files
create_missing_yarn_locks() {
    echo -e "\n${CYAN}Creating missing yarn.lock files:${NC}"
    local created_count=0
    
    # Minimal valid yarn.lock content
    local yarn_lock_content="# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"
    
    for extension_dir in extensions/*/; do
        if [ -d "$extension_dir" ]; then
            extension_name=$(basename "$extension_dir")
            package_json_path="${extension_dir}package.json"
            yarn_lock_path="${extension_dir}yarn.lock"
            
            if [ -f "$package_json_path" ] && [ ! -f "$yarn_lock_path" ]; then
                if echo "$yarn_lock_content" > "$yarn_lock_path"; then
                    echo -e "${GREEN}✓ Created yarn.lock for: $extension_name${NC}"
                    ((created_count++))
                else
                    echo -e "${RED}✗ Failed to create yarn.lock for: $extension_name${NC}"
                fi
            fi
        fi
    done
    
    echo -e "${GREEN}Created $created_count yarn.lock files${NC}"
}

# Main execution
check_missing_yarn_locks
missing_count=$?

if [ $missing_count -gt 0 ]; then
    echo -e -n "\n${YELLOW}Do you want to create the missing yarn.lock files? (y/n): ${NC}"
    read -r response
    
    case "$response" in
        [yY][eE][sS]|[yY])
            create_missing_yarn_locks
            echo -e "\n${YELLOW}Rechecking...${NC}"
            check_missing_yarn_locks > /dev/null
            ;;
        *)
            echo -e "${YELLOW}Skipped creating yarn.lock files${NC}"
            ;;
    esac
else
    echo -e "\n${GREEN}No action needed.${NC}"
fi

echo -e "\n${GREEN}Script completed.${NC}"
